#!/bin/sh

if [ -f /usr/local/nginx/logs/nginx.pid ]; then
    /usr/local/nginx/sbin/nginx -s quit
    rm -f /usr/local/nginx/logs/nginx.pid
fi

/usr/local/nginx/sbin/nginx -c /usr/local/nginx/conf/nginx-foreground.conf
